// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/cors/cors.d.ts
declare module "cors" {
    import express = require('express');

    namespace e {
        interface CorsOptions  {
            origin?: any;
            methods?: any;
            allowedHeaders?: any;
            exposedHeaders?: any;
            credentials?: boolean;
            maxAge?: number;
        }
    }

    function e(options?: e.CorsOptions): express.RequestHandler;
    export = e;
}