// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/empower/empower.d.ts
declare function empower(originalAssert:any, formatter:any, options?:empower.Options):any;

declare namespace empower {
    export interface Options {
        destructive?: boolean;
        modifyMessageOnRethrow?: boolean;
        saveContextOnRethrow?: boolean;
        patterns?: string[];
    }
}

declare module "empower" {
    export = empower;
}